---
- name: (SSH - 2FA-GA) Install Google Authenticator PAM Module
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libpam-google-authenticator

- name: (SSH - 2FA-GA) Configure PAM Authentication Module
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^@include common-auth'
    line: "#@include common-auth"
    state: present
    backrefs: yes
  notify: reload ssh

- name: (SSH - 2FA-GA) Enable Google Autnenticator PAM Module
  blockinfile:
    path: /etc/pam.d/sshd
    marker: "# {mark} Google Authenticator"
    state: present
    insertafter: EOF
    block: |
      auth required pam_google_authenticator.so nullok
  notify: reload ssh

- name: (SSH - 2FA-GA) Configure SSHD Service For 2FA
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: "ChallengeResponseAuthentication yes"
    state: present
    backrefs: yes
  notify: reload ssh

- name: (SSH - 2FA-GA) Enable PAM In SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM'
    line: "UsePAM yes"
    state: present
    backrefs: yes
  notify: reload ssh

- name: (SSH - 2FA-GA) Configure MFA On SSH Service
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} MFA Configuration"
    state: present
    insertafter: EOF
    block: |
      AuthenticationMethods publickey,keyboard-interactive
  notify: reload ssh
